// ─────────────────────────────────────────────────────────────────────────────
// ControlMapBuilder — NIST SP 800-53 Rev 5 control map + cato/control-map.yaml.
//
// PART OF: FORGE EVOLVE for TMPC, Cyber/cATO overlay (Stage 5).
//
// Links each STIG check class (and each cATO capability the overlay performs) to the
// 800-53 control(s) it provides evidence for. EvidenceRefs are the check RuleIds and the
// emitted artifact paths, so a reviewer can trace a control to concrete evidence.
// ─────────────────────────────────────────────────────────────────────────────

using System.Text;
using ForgeEvolve.Contracts;

namespace ForgeEvolve.Cato;

public static class ControlMapBuilder
{
    /// <summary>
    /// Build the control map from the legacy findings (which checks fired) plus the standing
    /// cATO capabilities (provenance, SBOM, developer testing/process). Only controls with at
    /// least one concrete evidence ref are emitted.
    /// </summary>
    public static IReadOnlyList<ControlMapping> Build(
        IReadOnlyList<StigFinding> legacyFindings,
        string sbomRelPath,
        string provenanceRelPath)
    {
        // Accumulate evidence refs per control id.
        var evidence = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
        var names = new Dictionary<string, string>(StringComparer.Ordinal);

        void Map(string controlId, string controlName, string evidenceRef)
        {
            if (!evidence.TryGetValue(controlId, out SortedSet<string>? set))
            {
                set = new SortedSet<string>(StringComparer.Ordinal);
                evidence[controlId] = set;
            }
            set.Add(evidenceRef);
            names[controlId] = controlName;
        }

        // Map each finding class → its primary control(s).
        foreach (StigFinding f in legacyFindings.DistinctBy(f => f.RuleId))
        {
            switch (f.RuleId)
            {
                case StigAnalyzer.VID_SqlInjection:
                    Map("SI-10", "Information Input Validation", f.RuleId);
                    Map("SA-11", "Developer Testing and Evaluation", f.RuleId);
                    break;
                case StigAnalyzer.VID_InputValidation:
                    Map("SI-10", "Information Input Validation", f.RuleId);
                    break;
                case StigAnalyzer.VID_OutputEncoding:
                    Map("SI-10", "Information Input Validation", f.RuleId);
                    break;
                case StigAnalyzer.VID_HardcodedCreds:
                    Map("IA-5", "Authenticator Management", f.RuleId);
                    Map("SC-28", "Protection of Information at Rest", f.RuleId);
                    break;
                case StigAnalyzer.VID_TlsCertValidation:
                    Map("SC-8", "Transmission Confidentiality and Integrity", f.RuleId);
                    Map("SC-13", "Cryptographic Protection", f.RuleId);
                    break;
            }
        }

        // Standing cATO capabilities (always present when the overlay runs).
        Map("AU-10", "Non-repudiation", provenanceRelPath);
        Map("CM-8", "System Component Inventory", sbomRelPath);
        Map("SA-15", "Development Process, Standards, and Tools", sbomRelPath);
        Map("SA-11", "Developer Testing and Evaluation", "cato/stig-before.json");
        Map("SA-11", "Developer Testing and Evaluation", "cato/stig-after.json");
        // SBOM + pinned deps also support supply-chain risk management.
        Map("SR-3", "Supply Chain Controls and Processes", sbomRelPath);

        return evidence.Select(kv => new ControlMapping
        {
            ControlId = kv.Key,
            ControlName = names[kv.Key],
            EvidenceRefs = kv.Value.ToList(),
        }).ToList();
    }

    /// <summary>Render the control map as YAML (cato/control-map.yaml).</summary>
    public static string ToYaml(IReadOnlyList<ControlMapping> map)
    {
        var sb = new StringBuilder();
        sb.Append("# FORGE EVOLVE for TMPC — NIST SP 800-53 Rev 5 control map\n");
        sb.Append("# Generated by ForgeEvolve.Cato (Cyber/cATO overlay). Each control lists the\n");
        sb.Append("# evidence refs (STIG check RuleIds and emitted artifact paths) supporting it.\n");
        sb.Append("framework: \"NIST SP 800-53 Rev 5\"\n");
        sb.Append("controls:\n");
        foreach (ControlMapping m in map)
        {
            sb.Append($"  - id: {YamlScalar(m.ControlId)}\n");
            sb.Append($"    name: {YamlScalar(m.ControlName)}\n");
            sb.Append("    evidence:\n");
            foreach (string e in m.EvidenceRefs)
                sb.Append($"      - {YamlScalar(e)}\n");
        }
        return sb.ToString();
    }

    private static string YamlScalar(string s)
    {
        // Quote when the value could be misparsed; otherwise emit bare.
        bool needsQuote = s.Length == 0 ||
                          s.IndexOfAny(new[] { ':', '#', '-', '{', '}', '[', ']', ',', '&', '*', '!', '|', '>', '\'', '"', '%', '@', '`' }) >= 0 ||
                          char.IsWhiteSpace(s[0]) || char.IsWhiteSpace(s[^1]);
        if (!needsQuote) return s;
        return "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
